// src/services/mockData.ts

import { Site, Ticket, Statistics, Asset, MaintenanceLog } from '../types';

export const mockSites: Site[] = [
  {
    id: '1',
    name: 'Solar Farm Alpha',
    location: 'Desert Valley, AZ',
    status: 'online',
    lastUpdated: new Date().toISOString(),
    coordinates: { latitude: 33.4484, longitude: -112.0740 },
    powerOutput: 2500,
    efficiency: 94.5,
    alerts: 0,
    assets: [],
  },
  {
    id: '2',
    name: 'Wind Station Beta',
    location: 'Mountain Ridge, CO',
    status: 'warning',
    lastUpdated: new Date(Date.now() - 3600000).toISOString(),
    coordinates: { latitude: 39.7392, longitude: -104.9903 },
    powerOutput: 1800,
    efficiency: 87.2,
    alerts: 2,
    assets: [],
  },
  {
    id: '3',
    name: 'Hydro Plant Gamma',
    location: 'River Bend, OR',
    status: 'online',
    lastUpdated: new Date(Date.now() - 1800000).toISOString(),
    coordinates: { latitude: 45.5152, longitude: -122.6784 },
    powerOutput: 3200,
    efficiency: 96.8,
    alerts: 0,
    assets: [],
  },
  {
    id: '4',
    name: 'Solar Grid Delta',
    location: 'Sunny Plains, CA',
    status: 'maintenance',
    lastUpdated: new Date(Date.now() - 7200000).toISOString(),
    coordinates: { latitude: 34.0522, longitude: -118.2437 },
    powerOutput: 0,
    efficiency: 0,
    alerts: 1,
    assets: [],
  },
  {
    id: '5',
    name: 'Wind Farm Epsilon',
    location: 'Coastal Hills, WA',
    status: 'online',
    lastUpdated: new Date(Date.now() - 900000).toISOString(),
    coordinates: { latitude: 47.6062, longitude: -122.3321 },
    powerOutput: 2100,
    efficiency: 91.3,
    alerts: 0,
    assets: [],
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'a1',
    name: 'Solar Panel Array 1',
    type: 'Solar Panel',
    status: 'operational',
    lastMaintenance: '2026-01-15',
    nextMaintenance: '2026-04-15',
    siteId: '1',
  },
  {
    id: 'a2',
    name: 'Inverter Unit 1',
    type: 'Inverter',
    status: 'operational',
    lastMaintenance: '2026-02-01',
    nextMaintenance: '2026-05-01',
    siteId: '1',
  },
  {
    id: 'a3',
    name: 'Wind Turbine 1',
    type: 'Turbine',
    status: 'operational',
    lastMaintenance: '2026-01-20',
    nextMaintenance: '2026-03-20',
    siteId: '2',
  },
  {
    id: 'a4',
    name: 'Generator Unit 1',
    type: 'Generator',
    status: 'maintenance',
    lastMaintenance: '2026-02-10',
    nextMaintenance: '2026-02-20',
    siteId: '2',
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 't1',
    title: 'Low power output on Solar Panel Array 1',
    description: 'Solar panel array showing reduced efficiency. Need to inspect for dust accumulation.',
    priority: 'medium',
    status: 'open',
    siteId: '1',
    siteName: 'Solar Farm Alpha',
    createdAt: '2026-02-14T08:30:00Z',
    updatedAt: '2026-02-14T08:30:00Z',
  },
  {
    id: 't2',
    title: 'Unusual vibration in Wind Turbine 1',
    description: 'Turbine exhibiting abnormal vibration levels. Possible bearing issue.',
    priority: 'high',
    status: 'in-progress',
    siteId: '2',
    siteName: 'Wind Station Beta',
    createdAt: '2026-02-13T14:20:00Z',
    updatedAt: '2026-02-14T09:15:00Z',
    assignedTo: 'Tech-001',
  },
  {
    id: 't3',
    title: 'Generator maintenance required',
    description: 'Scheduled maintenance for generator unit. Oil change and filter replacement needed.',
    priority: 'low',
    status: 'resolved',
    siteId: '2',
    siteName: 'Wind Station Beta',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-12T16:45:00Z',
    assignedTo: 'Tech-002',
  },
  {
    id: 't4',
    title: 'Communication system offline',
    description: 'Site monitoring system not responding. Network connectivity issue suspected.',
    priority: 'critical',
    status: 'in-progress',
    siteId: '4',
    siteName: 'Solar Grid Delta',
    createdAt: '2026-02-14T06:00:00Z',
    updatedAt: '2026-02-14T07:30:00Z',
    assignedTo: 'Tech-003',
  },
];

export const mockStatistics: Statistics = {
  totalSites: 5,
  activeSites: 4,
  totalPowerOutput: 9600,
  averageEfficiency: 93.9,
  openTickets: 4,
  criticalAlerts: 1,
  uptime: 98.5,
};

export const mockMaintenanceLogs: MaintenanceLog[] = [
  {
    id: 'm1',
    assetId: 'a1',
    assetName: 'Solar Panel Array 1',
    date: '2026-01-15',
    technician: 'John Smith',
    description: 'Cleaned solar panels, checked connections',
    images: [],
    status: 'completed',
  },
  {
    id: 'm2',
    assetId: 'a3',
    assetName: 'Wind Turbine 1',
    date: '2026-01-20',
    technician: 'Sarah Johnson',
    description: 'Lubricated bearings, inspected blades',
    images: [],
    status: 'completed',
  },
];